### ISSUE TITLE
FastMultiply

### ISSUE THREAD

**Issue by bauminator90** [bauminator90/FastMultiplication#2]
Am besten sollte überprüft werden, was hier nicht tut. Der Algorithmus gibt offensichtlich falsche Ergebnisse zurück. 

Ich vermute zudem, dass die Anpassung der z nicht korrekt ist.
Sollte analog zur Zulassungsarbeit S.53 ablaufen.

**Comment by dagophil** [comment]
Das Vorzeichen wird derzeit bei der Multiplikation ignoriert.

EDIT: FIXED

**Comment by dagophil** [comment]
Wieso sind die Koeffizienten in xcoeff vom Typ BadicRepresentation<2>? Müsste das nicht BadicRepresentation<B_new> sein?
Edit: Ah ok, es ist ein vector mit BadicRepresentation<2>. Ich glaube statt dem Vektor kann man BadicRepresentation<B_new> nehmen.

EDIT: Muss ein Vektor sein, weil ein Polynom erstellt wird und die einzelnen B-adischen Entwicklungen in dem Vektor die Koeffizienten des Polynoms darstellen.

**Comment by dagophil** [comment]
Der FastMultiply-Algorithmus an sich funktioniert. Es gibt nur ein Problem: Bei der Berechnung von z_hat wird rekursiv FastMultiply aufgerufen. Dabei hat die Rekursion die falsche Abbruchbedingung und wird daher unendlich oft aufgerufen. Wenn man die Rekursion verhindert, indem man FundamentalMultiply aufruft, kommt das richtige Ergebnis raus.

Wir müssen also genau ein Problem beheben: Wie wird die Rekursion richtig beendet?

EDIT: Ich vermute für h>3 oder so tut es, da h ja tatsächlich eine sinkende Folge ist. Das würde halt bedeuten, dass früher die "normale" Multiplikation genutzt wird. Ich teste das jetzt mal

**Comment by bauminator90** [comment]
Also wenn man die Bedingung der if-Abfrage auf h>4 setzt tut es lustiger Weise. Dann wird für riesige Eingaben zwar ewig gerechnet aber es kommt was raus :P Und zwar das richtige.
Die Laufzeit ist halt so ein Problem. Aber das kläre ich am Montag.
