### ISSUE TITLE
Wozu parameter q bei der schnellen Multiplikation?

### ISSUE THREAD

**Issue by dagophil** [bauminator90/FastMultiplication#5]
Bei der schnellen Multiplikation gibt es den Parameter q ("Logarithmus der 2-adischen Bitlänge"). Den kann man auch innerhalb der Funktion berechnen, dann muss man ihn nicht als Parameter übergeben.
Wieso ist das ein Parameter?

Edit: Ich glaube man muss q aufrunden. In der bisherigen Version wird abgerundet.
Edit2: Du benutzt max als Variablennamen. Da du überall using namespace std; machst, überschreibst du damit std::max. Das ist keine gute Idee... :D Ich empfehle, using namespace std; niemals in den globalen namespace zu packen, sondern stattdessen in jede Funktion.

**Comment by bauminator90** [comment]
Ist als Parameter gegeben, da n als Eingabeparameter im Originalalgorithmus vorgegeben war. Macht aber tatsächlich mehr Sinn es in die Funktion zu nehmen.
